name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true

channels:
  - channelName: mychannel
    contracts:
      - id: medicinecontract

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: "alice"
          clientPrivateKey:
            path: "../../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true
  - mspid: Org2MSP
    identities:
      certificates:
        - name: "bob"
          clientPrivateKey:
            path: "../../test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../../test-network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../../test-network/organizations/peerOrganizations/org2.example.com/connection-org2.yaml"
      discover: true